[package]
name = "duped"
version = "0.1.0"
edition = "2021"
description = "A library that helps you find file duplicates."
license = "GPL-3.0-or-later"

[dependencies]
blake3 = "1"
byte-unit = "5"
num_cpus = "1"
tracing = "0.1"
walkdir = "2"


[dev-dependencies]
tempfile = "3"
