[package]
name = "duped-cli"
version = "0.4.1"
edition = "2021"

[[bin]]
name = "duped"
path = "./src/main.rs"

[dependencies]
anyhow = "1"
byte-unit = "5"
duped.path = "../duped"
home = "0.5"
pico-args = "0.5"

[dev-dependencies]
tempfile = "3"
